headingLevels:
  - 2
  - 3
js: "return {\r\n\talignment: {\r\n\t  options: [\r\n\t\t'left',\r\n\t\t'center',\r\n\t\t'right',\r\n\t\t'justify',\r\n\t  ],\r\n\t},\r\n\ttoolbar: [ 'heading2', 'heading3', 'paragraph' ],\r\n\theading: {\r\n\t\toptions: [\r\n\t\t\t{ model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },\r\n\t\t\t{ model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' },\r\n\t\t\t{ model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },\r\n\t\t]\r\n\t},\r\n\tlink: {\r\n\t  toolbar: [\r\n\t\t'linkPreview',\r\n\t\t'|',\r\n\t\t'editLink',\r\n\t\t'linkProperties',\r\n\t\t'unlink',\r\n\t  ],\r\n\t  decorators: {\r\n\t\tisButton: {\r\n\t\t  mode: 'manual',\r\n\t\t  label: 'Button',\r\n\t\t  classes: 'button',\r\n\t\t},\r\n\t\tuseModal: {\r\n\t\t  mode: 'manual',\r\n\t\t  label: 'Open in Modal',\r\n\t\t  classes: 'useModal',\r\n\t\t},\r\n\t  },\r\n\t},\r\n}"
name: 'Block [title]'
toolbar:
  - heading
  - bold
  - italic
  - link
  - alignment
  - sourceEditing
