headingLevels:
  - 1
  - 2
js: "return {\r\n  alignment: {\r\n    options: [\r\n      'left',\r\n      'center',\r\n      'right',\r\n      'justify',\r\n    ],\r\n  },\r\n  toolbar: [ 'heading1', 'heading2', 'paragraph' ],\r\n  heading: {\r\n\t  options: [\r\n\t\t  { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },\r\n\t\t  { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },\r\n\t\t  { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },\r\n\t  ]\r\n  },\r\n  link: {\r\n    toolbar: [\r\n      'linkPreview',\r\n      '|',\r\n      'editLink',\r\n      'linkProperties',\r\n      'unlink',\r\n    ],\r\n    decorators: {\r\n      isButton: {\r\n        mode: 'manual',\r\n        label: 'Button',\r\n        classes: 'button',\r\n      },\r\n      useModal: {\r\n        mode: 'manual',\r\n        label: 'Open in Modal',\r\n        classes: 'useModal',\r\n      },\r\n    },\r\n  },\r\n}"
name: 'Enriched [title]'
toolbar:
  - heading
  - bold
  - italic
  - link
  - alignment
