altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  37c9b496-1012-439d-a20a-17a7c63d49a5:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            content: "# Secure Asset\r\n---"
            dateAdded: '2025-08-26T17:52:00+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: c68d04d0-8d49-4d7d-9322-d6785a65b8af
            userCondition: null
            width: 100
          -
            content: "## Overview\r\n\r\nAmet consectetur adipiscing posse **lorem ipsum dolor**. Deinde illa quae in congressu lorem ipsum dolor."
            dateAdded: '2025-08-26T17:52:00+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: f1272a13-08bb-4d94-a1e6-397a56de3fc0
            userCondition: null
            width: 25
          -
            dateAdded: '2025-08-26T17:52:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dd16cc0f-224b-4492-9c1b-1cc91a5d61f5 # Entry Details
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d9e7ad8-1ba7-400f-b0c0-c7e39cc7f946
            userCondition: null
            warning: null
            width: 75
          -
            content: '---'
            dateAdded: '2025-08-26T17:52:00+00:00'
            displayInPane: true
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 00cf1c79-0e01-4302-a3be-4ec2a865f721
            userCondition: null
            width: 25
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-04T20:29:22+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Internal Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f5e239c2-f1c4-4673-884e-f7a4aa883aa0
            userCondition: null
            warning: null
            width: 75
          -
            content: "## Preview Card\r\n\r\nLorem ipsum dolor sit amet consectetur adipiscing posse lorem ipsum dolor sit amet"
            dateAdded: '2025-08-26T17:52:00+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 83766eb5-ee70-4619-8974-1d4829cceec3
            userCondition: null
            width: 25
          -
            dateAdded: '2025-08-26T17:52:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c8176ffc-a976-4b43-b634-244a16039154 # Entry Card
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fdd3f46-37cd-42b2-8d91-09b1f664e5a9
            userCondition: null
            warning: null
            width: 75
          -
            content: "## Associations\r\n\r\nLorem ipsum dolor sit amet"
            dateAdded: '2025-08-26T17:52:00+00:00'
            displayInPane: true
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 3a35ef51-f3a1-4fd5-9740-d7f79c16fb05
            userCondition: null
            width: 25
          -
            dateAdded: '2025-08-26T17:52:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d3134fdd-a3cf-4946-83cf-d9061072af34 # Component
            handle: form
            includeInCards: false
            instructions: null
            label: 'Download Gate'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50688e88-4db3-4ebc-b707-1376a8323ab9
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-08-26T17:52:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ec92452d-10f2-4a41-a9ee-bf384facb572 # Topics
            handle: null
            includeInCards: false
            instructions: null
            label: 'Topics & Tags'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fcd6ed6e-e962-4d23-9ca7-85364117bb88
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 69d19c90-2fac-4e63-8cc6-5e9218cbba60
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            content: "## Transcript\r\n\r\nLorem ipsum dolor sit amet"
            dateAdded: '2025-08-26T17:52:00+00:00'
            displayInPane: true
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 182fbf76-7fc8-4cb0-ada6-2070677dfa05
            userCondition: null
            width: 25
          -
            dateAdded: '2025-08-26T17:52:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b24f1298-62ac-4de3-9ac3-32e644553bab # Code
            handle: transcript
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f8a2660-ae94-4aba-a72f-a0f9afc14c6c
            userCondition: null
            warning: null
            width: 75
          -
            content: "## JSON Data\r\n\r\nLorem ipsum dolor sit amet"
            dateAdded: '2025-08-26T17:52:00+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: d21d4f5f-7934-4d4b-8c7c-4869eb814926
            userCondition: null
            width: 25
          -
            dateAdded: '2025-08-26T17:52:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c3a40ee3-075b-405c-8e4e-6e676b5e7f64 # JSON
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 442b9385-d5e5-48c3-8ae2-c4a2639059f4
            userCondition: null
            warning: null
            width: 75
        name: Meta
        uid: 0ad68fb3-4261-4b7c-80bf-998adbaf76b9
        userCondition: null
fs: secureShare
handle: secure
name: 'Secure (Private)'
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: none
transformFs: ''
transformSubpath: _transforms
