altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  babf3b70-c4a6-452a-9a89-454d74961107:
    cardThumbAlignment: start
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-03T22:21:59+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Short Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 14c7cb0f-3cb5-4bea-b9f9-e21560ec4a67
            userCondition: null
            warning: null
            width: 50
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-11-03T22:21:59+00:00'
            disabled: false
            elementCondition:
              class: craft\elements\conditions\assets\AssetCondition
              conditionRules:
                -
                  class: craft\elements\conditions\assets\FileTypeConditionRule
                  operator: in
                  uid: 69382da0-66c4-4483-8618-acbceafda7d9
                  values:
                    - image
              elementType: craft\elements\Asset
              fieldContext: global
            id: null
            includeInCards: false
            instructions: null
            label: 'Image ALT Text'
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: c02bb390-d5a4-4b11-adcb-1a8b80b34c0c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-08-26T16:37:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 545f1fed-e750-457f-91f5-47b4faf56f85 # Title - Entry
            handle: null
            includeInCards: false
            instructions: null
            label: 'Long Name'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f86b45cd-f073-4485-9d0a-f9c7dd962107
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-21T16:42:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3d34d10-7741-40ba-9fae-27d87f771b4d # Content Summary
            handle: transcript
            includeInCards: false
            instructions: 'Transcribed log of audio content (if applicable)'
            label: Transcript
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc41880b-a53c-43c8-866b-f6539683431c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-26T16:37:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c8176ffc-a976-4b43-b634-244a16039154 # Entry Card
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ea51c3b-6e0b-4a68-866e-ea4719055762
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-26T16:37:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d3134fdd-a3cf-4946-83cf-d9061072af34 # Component
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67259dce-241c-4dbc-89d6-1a031d0b44a5
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-03T22:21:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ec92452d-10f2-4a41-a9ee-bf384facb572 # Topics
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a460b9c5-ca1f-4e35-b904-476b2cafaadc
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 6616191f-76a5-4562-ba53-2f017a4354cc
        userCondition: null
fs: websiteContent
handle: website
name: 'Content (Public)'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: custom
transformFs: websiteContent
transformSubpath: _transforms
