color: cyan
description: null
fieldLayouts:
  c8eb7d5c-36d7-46ea-9fc4-1346eff4656b:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            content: "# Article Overview\r\n---"
            dateAdded: '2025-09-03T14:36:36+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: cc88856f-f121-403c-a6d9-854495ae68fe
            userCondition: null
            width: 100
          -
            content: '## Details'
            dateAdded: '2025-09-03T14:36:36+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 46e2f08a-4010-4cd6-9739-e4cca03541ea
            userCondition: null
            width: 25
          -
            dateAdded: '2025-09-03T14:36:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dd16cc0f-224b-4492-9c1b-1cc91a5d61f5 # Entry Details
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4623a26f-8538-42ff-8632-1830b11fb975
            userCondition: null
            warning: null
            width: 75
          -
            content: '## Teaser Card'
            dateAdded: '2025-09-03T14:36:36+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 096a7b28-6a5a-4a08-8d36-b4ee2137483b
            userCondition: null
            width: 25
          -
            dateAdded: '2025-09-03T14:36:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c8176ffc-a976-4b43-b634-244a16039154 # Entry Card
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d10e7ef-242a-4d1d-b6ff-235066e3cc96
            userCondition: null
            warning: null
            width: 75
          -
            content: "---\r\n# Content Builders\r\n---"
            dateAdded: '2025-09-04T00:24:30+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 209e26f8-4d05-4bfb-9fd6-68a5290bdd98
            userCondition: null
            width: 100
          -
            dateAdded: '2025-06-18T16:59:25+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3764ff92-5c64-4fb5-927a-3359ffd070fa
            handle: null
            includeInCards: false
            instructions: null
            label: Type
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aed50933-51f7-46ed-b4ca-d676bb998613
            userCondition: null
            warning: null
            width: 50
          -
            content: "## Body Section\r\n\r\nThe **Body Builder** provides a set of content-first block types that can be combined to create complex layouts."
            dateAdded: '2025-09-03T14:36:36+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: b593d1e0-740f-4669-8ce6-27a1ce605eaa
            userCondition: null
            width: 25
          -
            dateAdded: '2024-08-27T18:11:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b4753be4-da84-4306-82e8-a9473ca5398f # Builder - Body
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b041d59-ea3c-4eb4-acb2-de55159201d2
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: 76f2ecbc-91b5-4717-ad35-6da2e9921685
        userCondition: null
handle: article
hasTitleField: false
icon: lightbulb
name: Article
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{ object.details.short }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
