color: pink
description: null
fieldLayouts:
  5fa6b54b-4ad9-4601-88a3-82f34623c4c9:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:fe461e60-4e7a-4092-a203-356e64382a1b'
      - 'layoutElement:9126c37a-c7f6-4285-8dd6-09c44450fa00'
      - 'layoutElement:005b2221-d670-4888-94e7-2553ba59a7cd'
      - 'layoutElement:9bcc112a-bfe0-4e71-9abf-6ee7b489cae7'
      - 'layoutElement:173b1ad5-a9cd-42ef-b8be-6ec4bdd9738a'
    tabs:
      -
        elementCondition: null
        elements:
          -
            content: "# Content Bits\r\n\r\n- Amet consectetur adipiscing posse lorem ipsum dolor sit amet\r\n- Deinde prima illa quae in congressu **lorem ipsum dolor ➜**"
            dateAdded: '2025-07-29T19:00:39+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 5e72da03-d135-48dd-bf62-104b16d3c5c6
            userCondition: null
            width: 50
          -
            dateAdded: '2025-07-10T22:17:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8fdbf754-ae65-42c5-ba4b-09de9259cad2 # Source
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b11b6e82-57f5-4333-a787-502a99862c26
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-10T22:17:23+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 8fdbf754-ae65-42c5-ba4b-09de9259cad2 # Source
                  layoutElementUid: b11b6e82-57f5-4333-a787-502a99862c26
                  operator: in
                  uid: 494b7c48-875c-4080-a174-aa14d2a4fe9d
                  values:
                    - embed
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 034fa9d1-d6c0-4c0e-8b5c-c149c6fc6265 # Bits
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d9ec6f5-8f3f-424c-b357-1dedc8ec92bd
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-07-11T16:03:06+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 8fdbf754-ae65-42c5-ba4b-09de9259cad2 # Source
                  layoutElementUid: b11b6e82-57f5-4333-a787-502a99862c26
                  operator: in
                  uid: d86f2173-f1aa-4509-b011-0c55805f52f1
                  values:
                    - collection
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 05a000c7-b7b3-48ca-be09-d6694316cd33 # Bit Collections
            handle: collection
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 005b2221-d670-4888-94e7-2553ba59a7cd
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-07-11T03:24:34+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 6c37e824-da2a-4405-89ac-0955125cf5cc
            userCondition: null
          -
            content: "## Style & Presentation ➜\r\n\r\n- **Frame** Quorum sine cau et sa fieri nihil putandum est quonam modo\r\n- **Format** Ut in voluptate sit, qui epuletur, in dolore, qui torqueatur"
            dateAdded: '2025-07-11T02:48:02+00:00'
            displayInPane: true
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: f2c6ca0d-387d-4909-a78d-bd6614ce19f4
            userCondition: null
            width: 50
          -
            dateAdded: '2025-07-10T22:17:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5635a1ac-adca-4a96-816a-7ae1b664bc4d # Frame
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99f0c55d-90dd-46c7-91be-e1a5fd6445cf
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-07-10T22:17:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 30d51977-2c56-424c-b45a-e20afdc7dfbb # Format
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 976cecc9-a504-4796-b99b-cf115d924838
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-07-28T18:23:42+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: c834d9f3-61ab-41d3-8b95-b875b66759e2
            userCondition: null
          -
            content: "## Secondary Content\r\n  \r\n- Amet consectetur adipiscing posse lorem ipsum dolor sit amet voluptate sit, qui epuletur ➜"
            dateAdded: '2025-07-28T18:23:42+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 6f8bef3d-e404-4aae-8439-093493fb913d
            userCondition: null
            width: 50
          -
            dateAdded: '2025-07-10T22:17:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
            handle: null
            includeInCards: false
            instructions: null
            label: 'Support Copy'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3ff30a1-cfff-4052-a5b4-e148c1a06de6
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-29T19:00:39+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\FieldConditionRule
                  operator: ni
                  uid: 0ff2fd6d-770f-4c5a-9cf8-1902b5c08200
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Builder - Header
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
                  layoutElementUid: a3ff30a1-cfff-4052-a5b4-e148c1a06de6
                  operator: in
                  uid: cabe9e8d-5e0c-4124-a59f-b143adac5cdb
                  values:
                    - copyLeftHeader
                    - copyRightHeader
                    - copyBelowHeader
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 7f04ec39-5b52-4784-a5cf-696c57c8b43a # Title - Block
            handle: intro
            includeInCards: true
            instructions: null
            label: Intro
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bcc112a-bfe0-4e71-9abf-6ee7b489cae7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-29T19:00:39+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\FieldConditionRule
                  operator: in
                  uid: 2bd525fd-4003-49f0-9ca0-0975bab4495d
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Builder - Header
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
                  layoutElementUid: a3ff30a1-cfff-4052-a5b4-e148c1a06de6
                  operator: in
                  uid: 07f89fef-0ef1-4d20-8548-7336dece0ae5
                  values:
                    - copyLeftHeader
                    - copyRightHeader
                    - copyBelowHeader
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 545f1fed-e750-457f-91f5-47b4faf56f85 # Title - Entry
            handle: introHeader
            includeInCards: true
            instructions: null
            label: Intro
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 173b1ad5-a9cd-42ef-b8be-6ec4bdd9738a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-29T19:00:39+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 83bd1a21-117d-4e25-83ff-6b2abd72f6ab
            userCondition: null
          -
            dateAdded: '2025-07-10T22:17:23+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\FieldConditionRule
                  operator: ni
                  uid: e763307b-23fe-4b6c-b267-5c5aa0bcac22
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Builder - Header
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
                  layoutElementUid: a3ff30a1-cfff-4052-a5b4-e148c1a06de6
                  operator: ni
                  uid: b629274c-4d27-4fe1-a92f-4d98f313851e
                  values:
                    - copyNone
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 7487ca3f-f51b-40e9-a538-40ab5b2c4a27 # Text [main]
            handle: null
            includeInCards: true
            instructions: null
            label: 'Body Copy'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe461e60-4e7a-4092-a203-356e64382a1b
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-07-29T19:00:39+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\FieldConditionRule
                  operator: in
                  uid: 5983b8d8-b3ce-4384-84c2-b2662e148802
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Builder - Header
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
                  layoutElementUid: a3ff30a1-cfff-4052-a5b4-e148c1a06de6
                  operator: ni
                  uid: f4f76f8d-49a2-47cb-835e-c97425460ed2
                  values:
                    - copyNone
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 335b1087-e2f6-41b1-b7de-f8d4b61d6c1e # Text [header]
            handle: null
            includeInCards: true
            instructions: null
            label: 'Body Copy'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9126c37a-c7f6-4285-8dd6-09c44450fa00
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0d782ae7-1101-445d-bf9c-f6bd46b23fe1
        userCondition: null
handle: bits
hasTitleField: false
icon: puzzle-piece
name: 'Block - Bits'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
