color: null
description: null
fieldLayouts:
  89296a1c-5559-43a3-8dea-a125ac30a48c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            content: "# Fragment Partial\r\n---"
            dateAdded: '2025-08-26T18:04:40+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: c54ecae5-2a84-4bc2-a595-fea7b54d34f4
            userCondition: null
            width: 100
          -
            content: "## Details\r\n\r\nLorem ipsum dolor sit amet, consectetur"
            dateAdded: '2025-08-28T17:06:42+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 4f96a91f-551e-4f8c-ba52-7d2f5db91e6a
            userCondition: null
            width: 25
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-28T17:04:38+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Reference Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6e4bbad6-100b-49ac-8713-5f52798c50e3
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-08-28T17:04:55+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 82c06ac8-8d32-4ab1-9c54-9201df846446
            userCondition: null
          -
            content: "## Block(s)\r\n---\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit"
            dateAdded: '2025-08-26T18:04:40+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 57f8fdb2-a5fc-414f-93ce-c76ae1cce963
            userCondition: null
            width: 25
          -
            dateAdded: '2025-06-27T16:42:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b4753be4-da84-4306-82e8-a9473ca5398f # Builder - Body
            handle: builder
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dac46000-c32b-4af3-b74d-4d643d9d4ac3
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: 7b6cfbc4-41c9-44e2-a7d6-41b9edf2286f
        userCondition: null
handle: builder
hasTitleField: true
icon: block-brick
name: Multi-Builder
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
