color: sky
description: null
fieldLayouts:
  3a5fcba1-7080-4398-abf6-19311eb4d489:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-03T22:21:51+00:00'
            elementCondition: null
            template: burton/docs/cp-note-collection.twig
            templateMode: site
            type: craft\fieldlayoutelements\Template
            uid: 11a46f43-8de5-403b-b0eb-086c32212362
            userCondition: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-03T22:21:51+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Collection Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c56a05a3-8a2a-4dcc-8672-dff79e54ad39
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-03T22:21:51+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: be22b344-498e-448e-a9c7-9d13ee238e0a
            userCondition: null
          -
            dateAdded: '2024-11-03T22:21:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4b104ed0-4b08-424b-a744-f9bbf418fc2f # Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 666635d9-2d5e-458c-9a43-8e47aa26ffb1
            userCondition: null
            warning: null
            width: 100
        name: 'Primary Content'
        uid: 2ca4add9-ebec-491f-a9b6-b090360c7775
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-03T22:21:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 545f1fed-e750-457f-91f5-47b4faf56f85 # Title - Entry
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd167373-c262-43d5-9d82-5cd99adc9382
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-03T22:21:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b54aca1f-5631-4f76-a248-e953c4ada5bd # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8a3b334-1d88-4a19-b72a-a831ecb6a97f
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-11-03T22:21:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 581b9070-f50c-49a0-91c7-2921437ad0fb # Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 301bd905-1ec9-45bc-b4d2-ae75e1cfa722
            userCondition: null
            warning: null
            width: 25
        name: 'Meta Details'
        uid: f9901616-135e-431a-9e50-9c2d7523aee6
        userCondition: null
handle: collectionImages
hasTitleField: true
icon: list-radio
name: 'Image Collection'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
