color: purple
description: null
fieldLayouts:
  adafea3e-6aa4-4818-8742-609fd8958c98:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-19T17:54:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e72b5d2e-e504-4e5e-8ee1-e1b2884d6e0e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-19T17:56:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d8bf6768-4ff5-4727-ac20-12f8f0344542 # Media
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d8fa6ee-bdaf-490f-b0bc-61c510ec91e5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-19T17:56:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a186d4ae-477e-4b06-868e-add5e8f44b0c # Embeds
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f280e1c0-0004-439a-9306-105b57b05724
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 90a91de6-daeb-49f4-ba6b-4cf6b6e8287e
        userCondition: null
handle: collectionMedia
hasTitleField: true
icon: photo-film-music
name: 'Media Collection'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
