color: orange
description: null
fieldLayouts:
  e71a5ed2-d4df-466a-b790-3b13aa7a2412:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:f59c1458-18da-4ac5-ba8e-0ba1353cff55'
      - 'layoutElement:3a2b3676-ed86-4681-8367-9d79cbae8ba7'
      - 'layoutElement:fb10dc32-2785-478a-becb-a1689fbea371'
      - 'layoutElement:9cee8f53-059c-4850-a006-4ccfda545173'
    tabs:
      -
        elementCondition: null
        elements:
          -
            content: "# Entry Cards\r\n\r\n- Amet consectetur adipiscing posse lorem ipsum dolor sit amet\r\n- Deinde prima illa quae in congressu **lorem ipsum dolor ➜**"
            dateAdded: '2025-07-28T22:23:38+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: f9a908d5-6eaf-4149-baf4-b18f9982ded0
            userCondition: null
            width: 50
          -
            dateAdded: '2025-06-18T21:27:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8fdbf754-ae65-42c5-ba4b-09de9259cad2 # Source
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 151eab56-e984-44e8-9324-fcc342782b8b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-03T22:21:50+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 8fdbf754-ae65-42c5-ba4b-09de9259cad2 # Source
                  layoutElementUid: 151eab56-e984-44e8-9324-fcc342782b8b
                  operator: in
                  uid: cc258bab-aa63-4e83-88dd-e7551a4ec1be
                  values:
                    - select
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: f240ce26-8d9d-4668-b18b-73371d5c5211 # Entries
            handle: null
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9cee8f53-059c-4850-a006-4ccfda545173
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-08-23T21:33:15+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 8fdbf754-ae65-42c5-ba4b-09de9259cad2 # Source
                  layoutElementUid: 151eab56-e984-44e8-9324-fcc342782b8b
                  operator: in
                  uid: d80188d6-b09e-480a-bd78-4e4c5814f76c
                  values:
                    - embed
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 71c33ae7-e68b-4a57-85cf-d73b1c55565c # Nested Entries
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 039b0fe4-0e53-46d8-87e4-a6cc0757e8a6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-03T22:21:50+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 8fdbf754-ae65-42c5-ba4b-09de9259cad2 # Source
                  layoutElementUid: 151eab56-e984-44e8-9324-fcc342782b8b
                  operator: in
                  uid: 308ae498-22e6-4eb8-a9a4-9636666f692b
                  values:
                    - collection
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 1fc4d14e-bdf2-4cfa-a95c-64f6dac73d40 # Entry Collections
            handle: null
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb10dc32-2785-478a-becb-a1689fbea371
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-07-11T15:57:42+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 81015fdc-08b6-4104-b779-aee9fbab3ee3
            userCondition: null
          -
            content: "## Style & Presentation ➜\r\n\r\n- **Frame** Quorum sine cau et sa fieri nihil putandum est quonam modo\r\n- **Format** Ut in voluptate sit, qui epuletur, in dolore, qui torqueatur"
            dateAdded: '2025-07-11T15:57:42+00:00'
            displayInPane: true
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: db9daa46-8574-41e0-82dd-8a4dacaed657
            userCondition: null
            width: 50
          -
            dateAdded: '2024-11-03T22:21:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5635a1ac-adca-4a96-816a-7ae1b664bc4d # Frame
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fd100c3-9941-4570-8969-0ee8b78a20af
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-06-14T20:04:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 30d51977-2c56-424c-b45a-e20afdc7dfbb # Format
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8d276d8-5b78-4e34-adca-81ee054b5ddf
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-07-28T18:24:43+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 2d678b42-5c9a-49fa-93e3-8f8664900167
            userCondition: null
          -
            content: "## Secondary Content\r\n  \r\n- Amet consectetur adipiscing posse lorem ipsum dolor sit amet voluptate sit, qui epuletur ➜"
            dateAdded: '2025-07-28T18:24:43+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 17d4d0e3-69a2-462c-b079-bb91b515dd75
            userCondition: null
            width: 50
          -
            dateAdded: '2024-11-03T22:21:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc7e6b90-0f58-415a-b6f2-86313eae7a65
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-28T23:02:18+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\FieldConditionRule
                  operator: ni
                  uid: 56490923-246b-427c-a07c-b9f2b5428e66
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Builder - Header
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
                  layoutElementUid: bc7e6b90-0f58-415a-b6f2-86313eae7a65
                  operator: in
                  uid: 678194ab-3c74-4f5b-bf3a-3c8516692f89
                  values:
                    - copyLeftHeader
                    - copyRightHeader
                    - copyBelowHeader
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 7f04ec39-5b52-4784-a5cf-696c57c8b43a # Title - Block
            handle: intro
            includeInCards: false
            instructions: null
            label: Intro
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 285f6be3-8132-44e7-a0b8-69afa00bfe21
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-28T23:02:18+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\FieldConditionRule
                  operator: in
                  uid: e6e5b969-fef8-4fc4-8e2a-cac3de60f0c7
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Builder - Header
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
                  layoutElementUid: bc7e6b90-0f58-415a-b6f2-86313eae7a65
                  operator: in
                  uid: 31e2fa05-efe9-4bbb-9737-08280ed834ce
                  values:
                    - copyLeftHeader
                    - copyRightHeader
                    - copyBelowHeader
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 545f1fed-e750-457f-91f5-47b4faf56f85 # Title - Entry
            handle: introHeader
            includeInCards: false
            instructions: null
            label: Intro
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 025d7ede-e4cb-41bc-a964-406605d6af6f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-28T22:37:15+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 225c3e3d-1017-4760-90c3-d4c6eaee371f
            userCondition: null
          -
            dateAdded: '2024-11-03T22:21:50+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\FieldConditionRule
                  operator: ni
                  uid: 5e9578f0-e34e-4e17-aa43-e4f18957df3c
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Builder - Header
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
                  layoutElementUid: bc7e6b90-0f58-415a-b6f2-86313eae7a65
                  operator: ni
                  uid: b5af9419-c258-4a52-910b-1e6f98f4b95a
                  values:
                    - copyNone
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 7487ca3f-f51b-40e9-a538-40ab5b2c4a27 # Text [main]
            handle: null
            includeInCards: true
            instructions: null
            label: 'Body Copy'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a2b3676-ed86-4681-8367-9d79cbae8ba7
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-11-03T22:21:50+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\FieldConditionRule
                  operator: in
                  uid: 008e39f3-e53c-473a-9aeb-5be87a019730
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Builder - Header
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
                  layoutElementUid: bc7e6b90-0f58-415a-b6f2-86313eae7a65
                  operator: ni
                  uid: f8e51501-a337-4fc4-8b00-3b1827360154
                  values:
                    - copyNone
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 335b1087-e2f6-41b1-b7de-f8d4b61d6c1e # Text [header]
            handle: null
            includeInCards: true
            instructions: null
            label: 'Body Copy'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f59c1458-18da-4ac5-ba8e-0ba1353cff55
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: 46e6a9a3-4c05-449f-a4c2-492c41a78ebb
        userCondition: null
handle: deck
hasTitleField: false
icon: cards
name: 'Block - Card'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
