color: null
description: null
fieldLayouts:
  d5987dad-8fc6-4016-8a6f-f88bdcfc6149:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-11T15:42:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 88fdcb93-d8c6-4625-807e-885199098b6c # Label
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2ede4e5-1d54-4f0b-9bb9-0aefcc044a66
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-06-27T16:42:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4b104ed0-4b08-424b-a744-f9bbf418fc2f # Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05b8915d-85a6-45a5-9e41-a84d08934d25
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-06-27T16:42:49+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 266a6486-e076-41ca-8329-2d2d420df62d
            userCondition: null
          -
            dateAdded: '2025-06-27T16:42:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3d34d10-7741-40ba-9fae-27d87f771b4d # Content Summary
            handle: null
            includeInCards: false
            instructions: null
            label: Copy
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5983dad4-8807-4bd1-9a4b-3a659008ae64
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-06-27T16:42:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b54aca1f-5631-4f76-a248-e953c4ada5bd # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4bcbbf21-6e8a-4e5a-bcb8-9679d3c0729e
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-06-27T16:42:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 581b9070-f50c-49a0-91c7-2921437ad0fb # Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 324b9f40-3cf0-453f-a5cf-55f84541dcc6
            userCondition: null
            warning: null
            width: 25
        name: 'Content Bit'
        uid: fc93ce85-8a48-4e3f-b1e4-636a7627734e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-06-27T16:46:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d554a8e7-e8ad-493b-aaa8-d611bf04b257 # Website / Content URL
            handle: source
            includeInCards: false
            instructions: null
            label: URL
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 393dc4c3-f74f-4d48-8d56-d0d83f7fd69a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-27T16:46:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c3a40ee3-075b-405c-8e4e-6e676b5e7f64 # JSON
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c9907ca-48ad-4d91-95b7-acca0a6ec48e
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: 759fb185-b29d-4b03-beb4-c42c5c43facc
        userCondition: null
handle: generic
hasTitleField: false
icon: bin-recycle
name: 'Generic Bit'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
