color: sky
description: null
fieldLayouts:
  322a0f34-1814-4e8d-a8e7-6095f590bb43:
    cardThumbAlignment: start
    cardView:
      - 'layoutElement:666e778e-9b90-4afb-ab01-46e052a7b848'
      - 'layoutElement:e30da91e-928a-429a-81ed-33da2acbabad'
      - 'layoutElement:10d999b9-f82d-4901-9c85-ae49b141c26b'
    tabs:
      -
        elementCondition: null
        elements:
          -
            content: "# Images\r\n\r\n- Amet consectetur adipiscing posse lorem ipsum dolor sit amet\r\n- Deinde prima illa quae in congressu **lorem ipsum dolor ➜**"
            dateAdded: '2025-07-29T16:48:56+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 4a18d98c-fe10-4794-b122-26d7cb094a23
            userCondition: null
            width: 50
          -
            dateAdded: '2025-06-18T21:34:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8fdbf754-ae65-42c5-ba4b-09de9259cad2 # Source
            handle: null
            includeInCards: false
            instructions: 'Ut in voluptate sit, qui epuletur, in dolore, qui torqueatur lorem'
            label: Source
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8dad99f-0cd3-44da-b933-80ebd3041066
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-03T22:21:51+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 8fdbf754-ae65-42c5-ba4b-09de9259cad2 # Source
                  layoutElementUid: e8dad99f-0cd3-44da-b933-80ebd3041066
                  operator: in
                  uid: b671a6c6-47db-4fc3-b60e-df9a0b7f61a9
                  values:
                    - select
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 4b104ed0-4b08-424b-a744-f9bbf418fc2f # Images
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39adec54-ab28-4bf4-84a9-c01b591629d5
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-07-11T15:54:46+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 8fdbf754-ae65-42c5-ba4b-09de9259cad2 # Source
                  layoutElementUid: e8dad99f-0cd3-44da-b933-80ebd3041066
                  operator: in
                  uid: 0212d7e4-07ac-4705-95b1-6b6e4b9c0be6
                  values:
                    - collection
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: f3cf4580-ee28-4e7e-b9c6-4177b508cdfc # Image Collections
            handle: collections
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 666e778e-9b90-4afb-ab01-46e052a7b848
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-11-03T22:21:51+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 518032ea-dbb4-44fb-b190-8057f4fd6666
            userCondition: null
          -
            content: "## Style & Presentation ➜\r\n\r\n- **Frame** Quorum sine cau et sa fieri nihil putandum est quonam modo\r\n- **Format** Ut in voluptate sit, qui epuletur, in dolore, qui torqueatur"
            dateAdded: '2025-07-11T15:54:46+00:00'
            displayInPane: true
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 3072ca9e-97ed-4d4e-ab34-ed3f20a11377
            userCondition: null
            width: 50
          -
            dateAdded: '2025-07-20T02:06:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5635a1ac-adca-4a96-816a-7ae1b664bc4d # Frame
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f10279b5-46c0-445b-ac37-730bf1264114
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-07-20T02:06:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 30d51977-2c56-424c-b45a-e20afdc7dfbb # Format
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eceb96cd-6dff-4b9d-94f6-4f0ebc95bc9d
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-07-20T02:22:54+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 8149bf60-8b2e-497a-9c89-adcb09d8aebe
            userCondition: null
          -
            content: "## Secondary Content\r\n  \r\n- Amet consectetur adipiscing posse lorem ipsum dolor sit amet voluptate sit, qui epuletur ➜"
            dateAdded: '2025-07-28T17:59:16+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 8b70e37d-5ecd-4410-b1c3-1e64003c174b
            userCondition: null
            width: 50
          -
            dateAdded: '2024-11-03T22:21:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db8622f2-0ec9-4de4-9f76-a2954648b67c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-26T23:06:35+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\FieldConditionRule
                  operator: ni
                  uid: 237a1b4d-5e29-4cf1-a60f-aa662e1e1484
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Builder - Header
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
                  layoutElementUid: db8622f2-0ec9-4de4-9f76-a2954648b67c
                  operator: in
                  uid: 0109410a-9b65-4726-a2bc-561f38e8bc86
                  values:
                    - copyLeftHeader
                    - copyRightHeader
                    - copyBelowHeader
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 7f04ec39-5b52-4784-a5cf-696c57c8b43a # Title - Block
            handle: intro
            includeInCards: false
            instructions: null
            label: Intro
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1fe60e9d-007f-4386-a5d0-4980a5d8b13c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-26T23:06:35+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\FieldConditionRule
                  operator: in
                  uid: 150e9539-1b2e-4a1f-9ee4-929436be8a4e
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Builder - Header
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
                  layoutElementUid: db8622f2-0ec9-4de4-9f76-a2954648b67c
                  operator: in
                  uid: 77bf854d-149b-4aa1-9681-13a11913ea34
                  values:
                    - copyLeftHeader
                    - copyRightHeader
                    - copyBelowHeader
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 545f1fed-e750-457f-91f5-47b4faf56f85 # Title - Entry
            handle: introHeader
            includeInCards: false
            instructions: null
            label: Intro
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3045d94-e628-4c64-a85f-6f5710e42c40
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-29T16:48:56+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 1c2d1fac-9cd3-4131-a2cd-a10a046dd49b
            userCondition: null
          -
            dateAdded: '2024-11-03T22:21:51+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\FieldConditionRule
                  operator: ni
                  uid: 74bfac06-c9d1-48c2-9346-2e236c45cced
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Builder - Header
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
                  layoutElementUid: db8622f2-0ec9-4de4-9f76-a2954648b67c
                  operator: ni
                  uid: 0bb39be5-2ff7-4cc3-9f11-8a566a132f48
                  values:
                    - copyNone
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 7487ca3f-f51b-40e9-a538-40ab5b2c4a27 # Text [main]
            handle: null
            includeInCards: true
            instructions: null
            label: 'Body Copy'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10d999b9-f82d-4901-9c85-ae49b141c26b
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-11-03T22:21:51+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\FieldConditionRule
                  operator: in
                  uid: 8607f88c-8f5d-4cdf-911a-81b5e377c76a
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Builder - Header
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
                  layoutElementUid: db8622f2-0ec9-4de4-9f76-a2954648b67c
                  operator: ni
                  uid: 9e9fbe69-bb5a-4337-a22f-9a74eecf9e51
                  values:
                    - copyNone
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 335b1087-e2f6-41b1-b7de-f8d4b61d6c1e # Text [header]
            handle: null
            includeInCards: true
            instructions: null
            label: 'Body Copy'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e30da91e-928a-429a-81ed-33da2acbabad
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: 3383902d-5fd0-4eb5-b3cb-d5798e3a4aad
        userCondition: null
handle: image
hasTitleField: false
icon: image
name: 'Block - Image'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
