color: purple
description: null
fieldLayouts:
  0043a478-7bc5-4a6f-b717-de689da18143:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:cd9863d6-70f6-4b2f-a1bb-98f5cf9bf95b'
      - 'layoutElement:55f3b644-fbc0-4473-8e78-cae35f7166e4'
      - 'layoutElement:7bca2240-b2e2-4ad4-b086-0f816c44ee12'
      - 'layoutElement:9526c500-4357-4b56-bef9-d88b8e65cf0b'
    tabs:
      -
        elementCondition: null
        elements:
          -
            content: "# Media Element\r\n\r\n- Amet consectetur adipiscing posse lorem ipsum dolor sit amet\r\n- Deinde prima illa quae in congressu **lorem ipsum dolor ➜**"
            dateAdded: '2025-07-29T17:33:20+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 8f7bc772-47e1-443d-af79-ff91018ad713
            userCondition: null
            width: 50
          -
            dateAdded: '2025-06-18T21:35:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8fdbf754-ae65-42c5-ba4b-09de9259cad2 # Source
            handle: null
            includeInCards: false
            instructions: "Ut in voluptate sit, qui epuletur, in dolore.\r\n\r\n"
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64375fe2-3446-41ef-adee-d4a6e4cb1874
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-03T22:21:50+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 8fdbf754-ae65-42c5-ba4b-09de9259cad2 # Source
                  layoutElementUid: 64375fe2-3446-41ef-adee-d4a6e4cb1874
                  operator: in
                  uid: 07238e90-4e5d-4efa-bbb1-0c77a5d25dcd
                  values:
                    - select
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: d8bf6768-4ff5-4727-ac20-12f8f0344542 # Media
            handle: null
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd9863d6-70f6-4b2f-a1bb-98f5cf9bf95b
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-11-03T22:21:50+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 8fdbf754-ae65-42c5-ba4b-09de9259cad2 # Source
                  layoutElementUid: 64375fe2-3446-41ef-adee-d4a6e4cb1874
                  operator: in
                  uid: 9188451a-eaa9-43d9-8106-4c5e31d3b79c
                  values:
                    - embed
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: a186d4ae-477e-4b06-868e-add5e8f44b0c # Embeds
            handle: null
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fc2b388-4ba3-49d8-9911-34a4eb7f889b
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-07-11T15:56:16+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 8fdbf754-ae65-42c5-ba4b-09de9259cad2 # Source
                  layoutElementUid: 64375fe2-3446-41ef-adee-d4a6e4cb1874
                  operator: in
                  uid: db029090-3f17-4423-9c70-6a35124ab0f7
                  values:
                    - collection
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: ce2e0ec7-6cd7-4c08-ad27-d3ba11952c70 # Media Collections
            handle: collections
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55f3b644-fbc0-4473-8e78-cae35f7166e4
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-11-03T22:21:50+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 9ca7bce8-bd92-4dba-8a3c-665119b81813
            userCondition: null
          -
            content: "## Style & Presentation ➜\r\n\r\n- **Frame** Quorum sine cau et sa fieri nihil putandum est quonam modo\r\n- **Format** Ut in voluptate sit, qui epuletur, in dolore, qui torqueatur"
            dateAdded: '2025-07-11T15:56:16+00:00'
            displayInPane: true
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 72c64e90-7c2a-4960-97ea-5ee02e0c6cac
            userCondition: null
            width: 50
          -
            dateAdded: '2024-11-03T22:21:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5635a1ac-adca-4a96-816a-7ae1b664bc4d # Frame
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f61f5747-389a-4042-8d5f-6c9ccb33b5df
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-06-14T20:07:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 30d51977-2c56-424c-b45a-e20afdc7dfbb # Format
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f82931c3-b106-417b-9a56-a8d3a9ffe6d8
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-07-21T17:51:27+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: c1e333cb-08c3-4bb4-87a2-8fe92c8c337f
            userCondition: null
          -
            content: "## Supporting Content\r\n  \r\nDeinde prima illa quae in congressu **lorem ipsum dolor ➜**\r\n\r\n---\r\n"
            dateAdded: '2025-07-28T18:30:52+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: db488556-f131-4202-934f-424254fff7d6
            userCondition: null
            width: 50
          -
            dateAdded: '2024-11-03T22:21:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58d78c0e-d03a-414b-8ab1-4fcb72befed0
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-29T17:33:20+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\FieldConditionRule
                  operator: ni
                  uid: 3a17eb2c-d9c8-4b27-bed7-4b8376b8dc65
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Builder - Header
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
                  layoutElementUid: 58d78c0e-d03a-414b-8ab1-4fcb72befed0
                  operator: in
                  uid: 3b78a800-644b-4ff4-8c25-0f98ad61738c
                  values:
                    - copyLeftHeader
                    - copyRightHeader
                    - copyBelowHeader
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 7f04ec39-5b52-4784-a5cf-696c57c8b43a # Title - Block
            handle: intro
            includeInCards: false
            instructions: null
            label: Intro
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98221511-795d-417f-a9aa-a610edb07072
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-29T17:33:20+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\FieldConditionRule
                  operator: in
                  uid: de757737-6018-464c-84e5-b974b5345d71
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Builder - Header
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
                  layoutElementUid: 58d78c0e-d03a-414b-8ab1-4fcb72befed0
                  operator: in
                  uid: 8166e056-6b8e-4d29-97b9-5d9043ed048a
                  values:
                    - copyLeftHeader
                    - copyRightHeader
                    - copyBelowHeader
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 545f1fed-e750-457f-91f5-47b4faf56f85 # Title - Entry
            handle: introHeader
            includeInCards: false
            instructions: null
            label: Intro
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1f1d262-8685-4e84-ae8a-955d1ab9da18
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-29T17:33:20+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: c439a909-2306-4644-85b5-d29de1490fcb
            userCondition: null
          -
            dateAdded: '2024-11-03T22:21:50+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\FieldConditionRule
                  operator: ni
                  uid: 788f9638-e43a-4ee9-a502-9aec554c2f62
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Builder - Header
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
                  layoutElementUid: 58d78c0e-d03a-414b-8ab1-4fcb72befed0
                  operator: ni
                  uid: 92e17fb6-f157-433f-984f-0afae14901bd
                  values:
                    - copyNone
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 7487ca3f-f51b-40e9-a538-40ab5b2c4a27 # Text [main]
            handle: null
            includeInCards: true
            instructions: null
            label: 'Body Copy'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9526c500-4357-4b56-bef9-d88b8e65cf0b
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-11-03T22:21:50+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\FieldConditionRule
                  operator: in
                  uid: 101a3de8-3daf-4b22-aa75-391ac9000b17
                  values:
                    - a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Builder - Header
                -
                  class: simplicateca\metasettings\fields\conditions\MetaSettingsDropdownConditionRule
                  fieldUid: 01cc4fd6-b198-40f9-84b8-c6bfb1cbdcaa # Secondary
                  layoutElementUid: 58d78c0e-d03a-414b-8ab1-4fcb72befed0
                  operator: ni
                  uid: 8753dc68-fb9a-4822-b5b6-88c35fbfd99e
                  values:
                    - copyNone
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 335b1087-e2f6-41b1-b7de-f8d4b61d6c1e # Text [header]
            handle: null
            includeInCards: true
            instructions: null
            label: 'Body Copy'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7bca2240-b2e2-4ad4-b086-0f816c44ee12
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: 408a25d4-998d-45d3-a875-c9038a60f203
        userCondition: null
handle: media
hasTitleField: false
icon: tv-retro
name: 'Block - Media'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
