color: rose
description: null
fieldLayouts:
  6c1321a4-38b4-4f46-92c7-1237ffa7db03:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            content: "# Publication Overview\r\n---"
            dateAdded: '2025-09-02T22:53:56+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 24123707-b371-4f6f-8eca-f2de16489b19
            userCondition: null
            width: 100
          -
            content: "## Details\r\n---"
            dateAdded: '2025-09-02T22:53:56+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 0f325136-2924-43d3-a43f-062d543a9df3
            userCondition: null
            width: 25
          -
            dateAdded: '2025-09-02T22:53:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dd16cc0f-224b-4492-9c1b-1cc91a5d61f5 # Entry Details
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb792dc5-6a7e-4402-90d7-b637057b8163
            userCondition: null
            warning: null
            width: 75
          -
            content: "## Teaser Card\r\n---"
            dateAdded: '2025-09-02T22:53:56+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 8dd74148-c5e4-4136-8f60-a8c22248de04
            userCondition: null
            width: 25
          -
            dateAdded: '2025-09-02T22:53:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c8176ffc-a976-4b43-b634-244a16039154 # Entry Card
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a59675c-9863-424c-9ba1-cf15a7708986
            userCondition: null
            warning: null
            width: 75
          -
            content: "## Branding\r\n---"
            dateAdded: '2025-09-02T22:53:56+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: ffff92e7-2aa0-4e2d-87d5-cac5f1c90a4e
            userCondition: null
            width: 25
          -
            dateAdded: '2025-09-02T22:53:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cd2e6879-b86b-4803-8657-7cc5dad06cfb # Entry Graphics
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06c87752-0969-47ef-affc-52ba4d75624d
            userCondition: null
            warning: null
            width: 75
        name: Overview
        uid: b9a694aa-5b29-42d0-9aab-d31c6dd7047e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            content: "# Publication Landing Page\r\n---"
            dateAdded: '2025-09-04T00:27:37+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: e038c301-1a62-4d6e-84b2-7da7f9a0758e
            userCondition: null
            width: 100
          -
            content: "## Hero\r\n\r\nThe **Header Builder** provides a set of content-first block types that can be combined to create complex layouts."
            dateAdded: '2025-09-02T22:53:56+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 17785ec3-7d85-4c39-a38a-4b5abd53d72e
            userCondition: null
            width: 25
          -
            dateAdded: '2025-09-02T22:53:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Builder - Header
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27d41e4e-1fe6-4a84-a7b8-aa848e4055b1
            userCondition: null
            warning: null
            width: 75
          -
            content: "## Body Content\r\n\r\nThe **Body Builder** provides a set of content-first block types that can be combined to create complex layouts."
            dateAdded: '2025-09-02T22:53:56+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: eb759d87-b2e6-4527-b8c6-83bb01ea4c33
            userCondition: null
            width: 25
          -
            dateAdded: '2025-09-02T22:53:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b4753be4-da84-4306-82e8-a9473ca5398f # Builder - Body
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d20073b8-ce6a-4c11-9933-cbcbcfe14a12
            userCondition: null
            warning: null
            width: 75
          -
            content: "## Secondary\r\n\r\nThe **Sidebar Builder** provides a set of content-first block types that can be combined to create complex layouts."
            dateAdded: '2025-09-02T22:53:56+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: e2523712-549d-47cf-8d73-58fd1639715c
            userCondition: null
            width: 25
          -
            dateAdded: '2025-09-02T22:53:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a6272176-e780-4d5e-90f2-df0115d1a324 # Builder - Sidebar
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ed835f2-242a-48fe-aa8f-8901aeb32982
            userCondition: null
            warning: null
            width: 75
        name: Homepage
        uid: c8293d70-cd30-4e66-8f35-fb4213b9271b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            content: "# Publication Entries\r\n---"
            dateAdded: '2025-09-04T00:27:37+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 4e2d0d16-b9dc-4456-92d6-f574a4393d7b
            userCondition: null
            width: 100
          -
            content: '## Manifest'
            dateAdded: '2025-09-04T00:34:34+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 80402de0-9b08-400e-b53a-4e1e4e1442ca
            userCondition: null
            width: 25
          -
            dateAdded: '2025-09-02T22:55:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 71c33ae7-e68b-4a57-85cf-d73b1c55565c # Nested Entries
            handle: entries
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84e9b8a0-903d-4abd-8acd-cd7b38707f2e
            userCondition: null
            warning: null
            width: 75
        name: Entries
        uid: f8004709-09a1-4b06-9faa-234c74d949d2
        userCondition: null
handle: publication
hasTitleField: false
icon: book-open
name: Publication
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{ object.details.short }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
