color: null
description: null
fieldLayouts:
  bb589d7d-986a-4917-aa3a-89765dc06c11:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-27T18:11:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Author Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6dbfd9fd-4a9c-4b47-bfff-94fc2c8030a2
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-27T18:11:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 88fdcb93-d8c6-4625-807e-885199098b6c # Label
            handle: null
            includeInCards: false
            instructions: null
            label: 'Position (Role, job title, etc.)'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a40b8770-93b3-4421-adbe-b8b570829da2
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-27T18:11:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3d34d10-7741-40ba-9fae-27d87f771b4d # Content Summary
            handle: null
            includeInCards: false
            instructions: null
            label: Quote
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d092636f-8b22-4922-b8a2-839662d540cb
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-27T18:11:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4b104ed0-4b08-424b-a744-f9bbf418fc2f # Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 183bfb75-b1ad-4de2-b9aa-13ba782e76b0
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-27T18:11:54+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 3599cd64-c574-4f16-b69a-d4d2fe02a535
            userCondition: null
          -
            dateAdded: '2024-08-27T18:11:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ec92452d-10f2-4a41-a9ee-bf384facb572 # Topics
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 420f9e16-016a-45f3-b259-d1eeceed2e1b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 668bc674-86b6-4e50-a07c-a1f3619796cf
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-06-27T16:49:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d554a8e7-e8ad-493b-aaa8-d611bf04b257 # Website / Content URL
            handle: source
            includeInCards: false
            instructions: null
            label: URL
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d711ec7-2566-44f5-8f78-72946a86e9c2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-27T16:49:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c3a40ee3-075b-405c-8e4e-6e676b5e7f64 # JSON
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c551963-f9c0-4d1e-b9e8-616f3bd32fe5
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: 772c8317-a16a-49d8-9ff6-05ffd2a1a806
        userCondition: null
handle: quote
hasTitleField: true
icon: quotes
name: Quote
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
