color: null
description: null
fieldLayouts:
  c648bca7-93fe-467d-ae34-bd716bab887d:
    cardThumbAlignment: start
    cardView:
      - 'layoutElement:a249a5a3-b8bd-49ce-9447-39d1affcc68b'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-11T15:39:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 88fdcb93-d8c6-4625-807e-885199098b6c # Label
            handle: statistic
            includeInCards: false
            instructions: null
            label: Statistic
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7fca1ca-7a2d-4127-9b7f-6c91fc9478c0
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-08-11T15:39:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 88fdcb93-d8c6-4625-807e-885199098b6c # Label
            handle: headline
            includeInCards: false
            instructions: null
            label: Headline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13c2f2e4-f8f0-4034-b6fe-8c4add0fa2ae
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-08-12T16:27:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b54aca1f-5631-4f76-a248-e953c4ada5bd # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3686d26-29aa-4a7b-b331-c738183d5f0c
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-08-11T15:39:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3d34d10-7741-40ba-9fae-27d87f771b4d # Content Summary
            handle: null
            includeInCards: true
            instructions: ' '
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a249a5a3-b8bd-49ce-9447-39d1affcc68b
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: 9a167567-b5a2-4736-b377-dfe68deb5a72
        userCondition: null
handle: stat
hasTitleField: false
icon: calculator
name: Statistic
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{{object.statistic}} - {{object.headline}}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
