color: null
description: null
fieldLayouts:
  eef57681-5e0b-4580-b05a-72dea32206f5:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            content: "# Topic\r\n---"
            dateAdded: '2025-09-02T23:09:33+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 1683de9f-ae0f-4bfe-89a5-19e5b246b172
            userCondition: null
            width: 100
          -
            content: '## Details'
            dateAdded: '2025-09-02T23:09:33+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 82fd1890-cce0-4b26-90d5-1ca2ce7fa2ac
            userCondition: null
            width: 25
          -
            dateAdded: '2025-09-02T23:09:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dd16cc0f-224b-4492-9c1b-1cc91a5d61f5 # Entry Details
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec6d139a-4185-426a-91c1-1d230887c55f
            userCondition: null
            warning: null
            width: 75
          -
            content: '## Teaser Card'
            dateAdded: '2025-09-02T23:09:33+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: d4d45e9a-81b3-4f76-95ad-b1a66ca7af37
            userCondition: null
            width: 25
          -
            dateAdded: '2025-09-02T23:09:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c8176ffc-a976-4b43-b634-244a16039154 # Entry Card
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13e0ac86-53e0-484d-9f05-97d3989750e1
            userCondition: null
            warning: null
            width: 75
          -
            content: '## Graphics'
            dateAdded: '2025-09-02T23:09:33+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 675c94ce-3cdb-4a69-a8ad-c3de2d65e3e2
            userCondition: null
            width: 25
          -
            dateAdded: '2025-09-02T23:09:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cd2e6879-b86b-4803-8657-7cc5dad06cfb # Entry Graphics
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4084cda-1a60-4d9d-8f17-35692575283c
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-09-02T23:09:33+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: c92e323c-bbd5-4ca1-aac1-8db8b958da27
            userCondition: null
          -
            content: '## Relationships'
            dateAdded: '2025-09-02T23:09:33+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 1f5073f5-0950-4d6c-9455-9e12abd8d075
            userCondition: null
            width: 25
          -
            dateAdded: '2025-09-02T23:09:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f240ce26-8d9d-4668-b18b-73371d5c5211 # Entries
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0acb9ea7-e2db-4d8f-8295-584ca52290d9
            userCondition: null
            warning: null
            width: 75
        name: Topic
        uid: cbf19f7c-2dd0-4513-bc6c-370b9bd8fe10
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            content: '## Header Builder'
            dateAdded: '2025-09-02T23:09:33+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 5361ae52-3745-4a98-a47a-73da77727b3d
            userCondition: null
            width: 25
          -
            dateAdded: '2024-11-03T22:21:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a03cf6a5-0e00-43cb-871c-3a37dde51a3e # Builder - Header
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e22de661-6d83-4cfe-bae8-6e96baf0941c
            userCondition: null
            warning: null
            width: 75
          -
            content: '## Body Builder'
            dateAdded: '2025-09-02T23:09:33+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: c3c42784-d831-4765-a7c4-112de7d1b63b
            userCondition: null
            width: 25
          -
            dateAdded: '2024-11-03T22:21:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b4753be4-da84-4306-82e8-a9473ca5398f # Builder - Body
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a29392b6-40b3-4b3d-bd85-41144fbab6a0
            userCondition: null
            warning: null
            width: 75
          -
            content: '## Sidebar Builder'
            dateAdded: '2025-09-02T23:09:33+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: fb5a4a15-1498-4a1a-af4f-a70171eff0a1
            userCondition: null
            width: 25
          -
            dateAdded: '2025-09-02T23:09:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a6272176-e780-4d5e-90f2-df0115d1a324 # Builder - Sidebar
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9cb38751-d65e-4300-8e6f-2aeeb0245048
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: 02d94838-1168-49d9-9901-127afee57e44
        userCondition: null
handle: topic
hasTitleField: false
icon: tags
name: Topic
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{ object.details.short }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
