allowPublicRegistration: true
deactivateByDefault: false
defaultGroup: ''
photoSubpath: users/
photoVolumeUid: 280486f4-01ac-42a0-8604-c20f6b62b5df # Content (Public)
require2fa: false
requireEmailVerification: true
validateOnPublicRegistration: true
