defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 21710874-0ba0-423c-82ec-7fd855abb982 # Live Query
  -
    uid: d7748b2a-ae79-4961-b103-a5aa758e39ab # Image Collection
  -
    uid: e97f398a-bad8-4b85-8315-c80ad3a3d118 # Entry Collection
  -
    uid: 333f26c0-28b8-46f7-8399-21a7bc623a2f # Media Collection
  -
    uid: 4b2a900b-f8d6-4b24-aee5-10ebc4051eb6 # External Feed
  -
    uid: ee5ec53b-b28e-44bf-bea0-3b8f8d20804e # Bit Collection
  -
    uid: bb561dd8-e748-4c68-9107-2ffd5db410d8 # Topic
handle: collections
maxAuthors: 1
name: Collections
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Result Preview'
      -
        - urlFormat
        - 'hub/collection/{{object.slug}}'
      -
        - refresh
        - '1'
propagationMethod: custom
siteSettings:
  5435578f-4317-4fbf-b24f-a5fd4d2e9f68: # French
    enabledByDefault: false
    hasUrls: false
    template: null
    uriFormat: null
  d34bee8e-bf22-451d-8339-a4342630833d: # English
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  e7f9ef82-aa7c-4def-8477-dbe7648488b5: # Alternate
    enabledByDefault: false
    hasUrls: false
    template: null
    uriFormat: null
type: channel
