columnSuffix: null
handle: bitCollections
instructions: null
name: 'Bit Collections'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
      -
        - conditionRules
        -
          -
            __assoc__:
              -
                - class
                - craft\elements\conditions\entries\TypeConditionRule
              -
                - uid
                - fafea1ec-cdfa-405d-af57-aa434f95b6ad
              -
                - operator
                - in
              -
                - values
                -
                  - 1eb561c2-313a-4ea5-9332-dd8effd8eb73 # Generic Bit
                  - ad3c4465-2c99-4028-82f5-cd2d63371663 # FAQ
                  - 066383d2-4c3e-415b-be7e-93c6a4c5471b # Quote
                  - b9df713e-1b28-462e-b65f-03198b663096 # Statistic
  selectionLabel: 'Choose Collection'
  showCardsInGrid: false
  showSearchInput: true
  showSiteMenu: false
  showUnpermittedEntries: false
  showUnpermittedSections: false
  sources:
    - 'section:667ee826-8732-4bc8-8dbe-b7aefad82b15' # Collections
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
