columnSuffix: null
handle: card
instructions: null
name: 'Entry Card'
searchable: true
settings:
  fieldLayouts:
    __assoc__:
      -
        - 5ffcae51-db0d-455b-a0b5-5aceadcd68c6
        -
          __assoc__:
            0:
              - tabs
              -
                -
                  __assoc__:
                    0:
                      - name
                      - Content
                    1:
                      - uid
                      - fe235041-85f9-4720-bb30-a06d9b379bcb
                    4:
                      - elements
                      -
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            2:
                              - label
                              - Image
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 50
                            10:
                              - dateAdded
                              - '2025-08-11T16:01:38+00:00'
                            11:
                              - uid
                              - 763e5dce-469f-40b8-b525-fb79a33a1624
                            14:
                              - fieldUid
                              - 4b104ed0-4b08-424b-a744-f9bbf418fc2f # Images
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            2:
                              - label
                              - Copy
                            3:
                              - instructions
                              - ' '
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 75
                            10:
                              - dateAdded
                              - '2025-08-11T16:01:38+00:00'
                            11:
                              - uid
                              - 1fe534e9-4038-476d-97bd-b36b826485a4
                            14:
                              - fieldUid
                              - f3d34d10-7741-40ba-9fae-27d87f771b4d # Content Summary
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - autoSummary
                            2:
                              - label
                              - 'Auto Summary'
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 25
                            10:
                              - dateAdded
                              - '2025-08-11T17:12:45+00:00'
                            11:
                              - uid
                              - 24ffcf33-f19d-4317-955d-c342695e3685
                            14:
                              - fieldUid
                              - ea50810e-421f-4332-8d5b-0fa6f1a3d7e0 # Enable
            3:
              - cardThumbAlignment
              - end
  viewMode: grouped
translationKeyFormat: null
translationMethod: site
type: craft\fields\ContentBlock
