columnSuffix: null
handle: collections
instructions: null
name: 'Entry Collections'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
      -
        - conditionRules
        -
          -
            __assoc__:
              -
                - class
                - craft\elements\conditions\entries\TypeConditionRule
              -
                - uid
                - a2162932-d645-4f91-bf62-6af9488f90be
              -
                - operator
                - in
              -
                - values
                -
                  - 21710874-0ba0-423c-82ec-7fd855abb982 # Live Query
                  - 4b2a900b-f8d6-4b24-aee5-10ebc4051eb6 # External Feed
                  - e97f398a-bad8-4b85-8315-c80ad3a3d118 # Entry Collection
  selectionLabel: Choose
  showCardsInGrid: true
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedEntries: false
  showUnpermittedSections: false
  sources:
    - 'section:667ee826-8732-4bc8-8dbe-b7aefad82b15' # Collections
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
