columnSuffix: null
handle: entries
instructions: null
name: Entries
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
      -
        - conditionRules
        -
          -
            __assoc__:
              -
                - class
                - craft\elements\conditions\entries\TypeConditionRule
              -
                - uid
                - cc5635aa-fc1f-4883-bbd1-564f3b7f5ec6
              -
                - operator
                - in
              -
                - values
                -
                  - 99d1e742-e9ee-4468-8f52-06f9672d8f68 # Page
                  - bb561dd8-e748-4c68-9107-2ffd5db410d8 # Topic
                  - 98843cde-e128-4799-a8dd-1862eba69b21
                  - 16eeaaf8-6778-46b1-887b-f4a83630cda3
                  - c1ea9486-a2c9-4169-9858-144fd21c25b9 # Article
                  - f7e61633-c292-4302-a0d2-ca73da792fcb
                  - 041e750b-ab10-4fb9-a87b-41acf128aae2
                  - 4df7052c-989e-4e15-8d24-31029f8fd2f6
                  - 215f4c77-1c97-456d-ac1a-d390d0f0cd64
                  - 8209c5fd-6e8c-45d3-8dc2-b44a991dc31e
                  - 773096ce-2142-42b4-9cf9-a945483e7609
                  - 16a6d54f-3574-4ebb-9d59-e06c13308432
  selectionLabel: Choose
  showCardsInGrid: true
  showSearchInput: true
  showSiteMenu: false
  showUnpermittedEntries: false
  showUnpermittedSections: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
