columnSuffix: null
handle: format
instructions: 'Deinde prima illa quae in congressu lorem ipsum'
name: Format
searchable: false
settings:
  configFile: _burton/local/settings/block.format.twig
  configJson: ''
  configTwig: ''
  customOptions: false
  mode: file
  options:
    -
      __assoc__:
        -
          - label
          - Grid
        -
          - value
          - grid
    -
      __assoc__:
        -
          - label
          - Carousel
        -
          - value
          - carousel
    -
      __assoc__:
        -
          - label
          - 'Collapser (Collapsing Panels)'
        -
          - value
          - collapser
    -
      __assoc__:
        -
          - label
          - 'Default (Simple, Seamless, Basic Image, Basic Media, Basic Text)'
        -
          - value
          - default
    -
      __assoc__:
        -
          - label
          - Spotlight
        -
          - value
          - spotlight
    -
      __assoc__:
        -
          - label
          - 'Index (Entry Index)'
        -
          - value
          - index
    -
      __assoc__:
        -
          - label
          - Interactive
        -
          - value
          - interactive
    -
      __assoc__:
        -
          - label
          - Multivariate
        -
          - value
          - multivariate
    -
      __assoc__:
        -
          - label
          - 'Gallery (Image Gallery, Media Gallery)'
        -
          - value
          - gallery
translationKeyFormat: null
translationMethod: none
type: simplicateca\metasettings\fields\MetaSettingsField
