columnSuffix: null
handle: frame
instructions: 'Amet con sectetur adi piscing posse lorem ipsum'
name: Frame
searchable: false
settings:
  configFile: _burton/local/settings/block.frame.twig
  configJson: ''
  configTwig: ''
  customOptions: false
  mode: file
  options:
    -
      __assoc__:
        -
          - label
          - Default
        -
          - value
          - default
    -
      __assoc__:
        -
          - label
          - Themed
        -
          - value
          - themed
    -
      __assoc__:
        -
          - label
          - Inherit
        -
          - value
          - inherit
translationKeyFormat: null
translationMethod: none
type: simplicateca\metasettings\fields\MetaSettingsField
