columnSuffix: null
handle: icon
instructions: null
name: Icon
searchable: false
settings:
  fullGraphqlData: false
  includeProIcons: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Icon
