columnSuffix: null
handle: text2
instructions: null
name: 'Text (With Bits)'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: 54bdf500-79d2-4c24-9147-1e3da8064473 # converterPriority: 'high',Text [main]
  createButtonLabel: null
  defaultTransform: null
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 1eb561c2-313a-4ea5-9332-dd8effd8eb73 # Generic Bit
    -
      __assoc__:
        -
          - uid
          - 066383d2-4c3e-415b-be7e-93c6a4c5471b # Quote
  expandEntryButtons: true
  fullGraphqlData: true
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
