columnSuffix: null
handle: time
instructions: null
name: Time
searchable: false
settings:
  max: '18:00'
  min: '06:00'
  minuteIncrement: 30
translationKeyFormat: null
translationMethod: none
type: craft\fields\Time
