columnSuffix: null
handle: titleEnriched
instructions: null
name: 'Title - Entry'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: c79e1e50-f4c9-4875-af8a-4a1be47d3c09 # Enriched [title]
  createButtonLabel: null
  defaultTransform: null
  expandEntryButtons: false
  fullGraphqlData: false
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: 150
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
